/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormTransaction;

import static FormTransaction.FormMakanan.stok1;
import static FormTransaction.FormMakanan.stok2;
import static FormTransaction.FormMakanan.stok3;
import static FormTransaction.FormMakanan.stok4;
import static FormTransaction.FormMakanan.stok5;
import static FormTransaction.FormMakanan.stok6;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author KRISNA
 */
public class FormMinuman extends javax.swing.JPanel {

    Connection conn;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form FormMakanan
     * @throws java.sql.SQLException
     */
    public FormMinuman() throws SQLException {
        initComponents();
        initCount();
    }

    public void initCount() throws SQLException {
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/mbaknis", "root", "");
            String sql = "SELECT nama_menu FROM stok_menu WHERE id_menu = 7";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                jLabel2.setText(rs.getString(1));
            }

            sql = "SELECT jumlah_menu FROM stok_menu WHERE id_menu = 7";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                stokm1.setText(rs.getString(1));
            }

            sql = "SELECT nama_menu FROM stok_menu WHERE id_menu = 8";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                jLabel3.setText(rs.getString(1));
            }

            sql = "SELECT jumlah_menu FROM stok_menu WHERE id_menu = 8";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                stokm2.setText(rs.getString(1));
            }

            sql = "SELECT nama_menu FROM stok_menu WHERE id_menu = 9";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                jLabel4.setText(rs.getString(1));
            }

            sql = "SELECT jumlah_menu FROM stok_menu WHERE id_menu = 9";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                stokm3.setText(rs.getString(1));
            }

            sql = "SELECT nama_menu FROM stok_menu WHERE id_menu = 10";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                jLabel5.setText(rs.getString(1));
            }

            sql = "SELECT jumlah_menu FROM stok_menu WHERE id_menu = 10";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                stokm4.setText(rs.getString(1));
            }

            sql = "SELECT nama_menu FROM stok_menu WHERE id_menu = 11";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                jLabel6.setText(rs.getString(1));
            }

            sql = "SELECT jumlah_menu FROM stok_menu WHERE id_menu = 11";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                stokm5.setText(rs.getString(1));
            }

            sql = "SELECT nama_menu FROM stok_menu WHERE id_menu = 12";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                jLabel7.setText(rs.getString(1));
            }

            sql = "SELECT jumlah_menu FROM stok_menu WHERE id_menu = 12";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                stokm6.setText(rs.getString(1));
            }

        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stokm6.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        add(stokm6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 70, -1));

        stokm1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        add(stokm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 60, -1));

        stokm2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        add(stokm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 60, -1));

        stokm3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        add(stokm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 70, -1));

        stokm4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        add(stokm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 60, -1));

        stokm5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        add(stokm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 60, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 80, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setText("jLabel2");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 80, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setText("jLabel2");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 80, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel5.setText("jLabel2");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 124, 80, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel6.setText("jLabel2");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 80, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel7.setText("jLabel2");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageForm/FormMinuman.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static final javax.swing.JTextField stokm1 = new javax.swing.JTextField();
    public static final javax.swing.JTextField stokm2 = new javax.swing.JTextField();
    public static final javax.swing.JTextField stokm3 = new javax.swing.JTextField();
    public static final javax.swing.JTextField stokm4 = new javax.swing.JTextField();
    public static final javax.swing.JTextField stokm5 = new javax.swing.JTextField();
    public static final javax.swing.JTextField stokm6 = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}
