/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formAdmin;

import FormTransaction.FormMakanan;
import FormTransaction.FormMinuman;
//import java.awt.HeadlessException;
//import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
//import java.sql.Statement;
//import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
//import net.sf.jasperreports.engine.JRException;
//import net.sf.jasperreports.engine.JasperCompileManager;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.engine.JasperReport;
//import net.sf.jasperreports.engine.design.JasperDesign;
//import net.sf.jasperreports.view.JasperViewer;
//import pesanDialog.simpan;
import transisi.TransisiForm;

/**
 *
 * @author KRISNA
 */
public class FormAdminReport extends TransisiForm {

    FormAdminTotalBersih adb;
    Connection conn;
    ResultSet rs = null;
    PreparedStatement pst = null;
//    HashMap mp = new HashMap();
//    JasperReport jpr;
//    JasperPrint jprint;
//    JasperDesign jd;
    /**
     * Creates new form Form
     */
    FormMakanan fmakanan;
    FormMinuman fminuman;

    public FormAdminReport() throws SQLException {
        initComponents();
        adb = new FormAdminTotalBersih();
        panelBersih.add(adb);
        adb.setVisible(false);
        table();
        initTotal();
        table.fixTable(jScrollPane1);
        DefaultTableModel mode = (DefaultTableModel) table.getModel();
    }

    public void initTotal() {
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/mbaknis", "root", "");
            String sql = "select sum(pembayaran) from transaksi";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                total.setText("Rp."+rs.getString(1));
            }
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBersih = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new customtable.CustomTable();
        btn_ubah = new swing.Button();
        year = new javax.swing.JTextField();
        month = new javax.swing.JTextField();
        day = new javax.swing.JTextField();
        button1 = new swing.Button();
        total = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1050, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBersih.setOpaque(false);
        add(panelBersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1050, 530));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 450, 180));

        btn_ubah.setBackground(new java.awt.Color(73, 255, 90));
        btn_ubah.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubah.setText("Cari");
        btn_ubah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 360, 40));

        year.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                yearKeyReleased(evt);
            }
        });
        add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 220, 30));

        month.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                monthKeyReleased(evt);
            }
        });
        add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 220, 30));

        day.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dayKeyReleased(evt);
            }
        });
        add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 220, 30));

        button1.setBackground(new java.awt.Color(105, 152, 171));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Pendapatan");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 190, 40));

        total.setBackground(new java.awt.Color(0, 0, 0));
        total.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 190, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageForm/AdminLaporanPendapatan.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void dayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dayKeyReleased
        // TODO add your handling code here:
        try {
            int har = Integer.parseInt(day.getText());
        } catch (NumberFormatException ex) {
            day.setText(null);
        }
    }//GEN-LAST:event_dayKeyReleased

    private void monthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monthKeyReleased
        // TODO add your handling code here:
        try {
            int har = Integer.parseInt(month.getText());
        } catch (NumberFormatException ex) {
            month.setText(null);
        }
    }//GEN-LAST:event_monthKeyReleased

    private void yearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearKeyReleased
        // TODO add your handling code here:
        try {
            int har = Integer.parseInt(year.getText());
        } catch (NumberFormatException ex) {
            year.setText(null);
        }
    }//GEN-LAST:event_yearKeyReleased

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        adb.setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        try {
            String sql = "select tanggal_keluar,pembayaran\n"
                    + "from transaksi\n"
                    + "where day(tanggal_keluar) = '" + day.getText() + "' OR month(tanggal_keluar) = '" + month.getText() + "' OR year(tanggal_keluar) = '" + year.getText() + "'";
            java.sql.Connection konek = (Connection) koneksi.configDB();
            java.sql.PreparedStatement pstt = konek.prepareStatement(sql);
            java.sql.ResultSet rss = pstt.executeQuery(sql);
            table();
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Tanggal Pendapatan");
            model.addColumn("Nominal");

            while (rss.next()) {
                model.addRow(new Object[]{rss.getString(1), rss.getString(2)
                });
                table.setModel(model);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btn_ubahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btn_ubah;
    private swing.Button button1;
    private javax.swing.JTextField day;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField month;
    private javax.swing.JPanel panelBersih;
    private customtable.CustomTable table;
    private javax.swing.JLabel total;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables

    private void table() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Harga Makanan");
        model.addColumn("Nama Pelanggan");
        model.addColumn("Tanggal Pembelian");

        try {
            String sql = "SELECT pembayaran,nama_pelanggan,tanggal_keluar FROM transaksi";
            java.sql.Connection konek = (Connection) koneksi.configDB();
            pst = konek.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1),
                    rs.getString(2), rs.getString(3)
                });
                table.setModel(model);
            }
        } catch (SQLException e) {
        }
    }
}
