/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formAdmin;

import transisi.TransisiForm;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import pesanDialog.BerhasilHapus;
import pesanDialog.BerhasilUbah;
import pesanDialog.GagalHapus;
import pesanDialog.GagalUbah;

/**
 *
 * @author KRISNA
 */
public class FormAdminSetting extends TransisiForm {

    /**
     * Creates new form Form
     */
    public FormAdminSetting() {
        initComponents();
        table();
        table.fixTable(jScrollPane2);
        DefaultTableModel mode = (DefaultTableModel) table.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ubah1 = new swing.Button();
        btn_hapus1 = new swing.Button();
        id_login = new javax.swing.JTextField();
        role = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new customtable.CustomTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ubah1.setBackground(new java.awt.Color(73, 255, 90));
        btn_ubah1.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubah1.setText("Ubah");
        btn_ubah1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ubah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubah1ActionPerformed(evt);
            }
        });
        add(btn_ubah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 100, 40));

        btn_hapus1.setBackground(new java.awt.Color(255, 61, 61));
        btn_hapus1.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus1.setText("Hapus");
        btn_hapus1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus1ActionPerformed(evt);
            }
        });
        add(btn_hapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 100, 40));
        add(id_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 220, 30));

        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });
        add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 220, 30));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 220, 30));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 220, 30));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 380, 250));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageForm/AdminSetting.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int baris = table.getSelectedRow();
        if (baris != 1);
        {
            String id_log = table.getValueAt(baris, 0).toString();
            id_login.setText(id_log);
            String usern = table.getValueAt(baris, 1).toString();
            username.setText(usern);
            String pass = table.getValueAt(baris, 2).toString();
            password.setText(pass);
            String rol = table.getValueAt(baris, 3).toString();
            role.setText(rol);
            ;
        }
    }//GEN-LAST:event_tableMouseClicked

    private void btn_ubah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubah1ActionPerformed
        try {
            String sql = "UPDATE login SET id_login = '" + id_login.getText() + "', username = '" + username.getText() + "',password = '" + password.getText() + "',role = '" + role.getText() + "' WHERE id_login = '" + id_login.getText() + "'";
            String sql1 = "delete from staff where id_login = '"+id_login+"'";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.PreparedStatement pst1 = conn.prepareStatement(sql1);
            pst.execute();
            pst1.execute();
            BerhasilUbah ub = new BerhasilUbah();
            ub.setVisible(true);
            table();
        } catch (HeadlessException | SQLException e) {

            GagalUbah gu = new GagalUbah();
            gu.setVisible(true);
        }
        table();
    }//GEN-LAST:event_btn_ubah1ActionPerformed

    private void btn_hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus1ActionPerformed
        try {
            String sql = "DELETE FROM login WHERE id_login = '" + id_login.getText() + "'";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            BerhasilHapus bh = new BerhasilHapus();
            bh.setVisible(true);
        } catch (HeadlessException | SQLException e) {
            GagalHapus gh = new GagalHapus();
            gh.setVisible(true);
        }
        table();
    }//GEN-LAST:event_btn_hapus1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btn_hapus1;
    private swing.Button btn_ubah1;
    private javax.swing.JTextField id_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField password;
    private javax.swing.JTextField role;
    private customtable.CustomTable table;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    private void table() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Login");
        model.addColumn("username");
        model.addColumn("password");
        model.addColumn("role");

        try {
            String sql = "SELECT * FROM login where role = 'Staff'";
            java.sql.Connection konek = (Connection) koneksi.configDB();
            java.sql.PreparedStatement pst = konek.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1),
                    rs.getString(2), rs.getString(3), rs.getString(4)
                });
                table.setModel(model);
            }
        } catch (SQLException e) {
        }
    }
}
