/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formAdmin;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import pesanDialog.BerhasilHapus;
import pesanDialog.BerhasilUbah;
import pesanDialog.GagalHapus;
import pesanDialog.GagalUbah;
import pesanDialog.simpan;

/**
 *
 * @author HP
 */
public class FormAdminTotalBersih extends javax.swing.JPanel {

    Connection conn;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form FormAdminDetailStok
     */
    public FormAdminTotalBersih() {
        initComponents();
        initTotal();
        table();
        table.fixTable(jScrollPane2);
        DefaultTableModel mode = (DefaultTableModel) table.getModel();
    }

    public void initTotal() {
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/mbaknis", "root", "");
            String sql = "SELECT pendapatan_bersih FROM income ORDER BY id_income DESC LIMIT 1";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                total_bersih.setText("Rp."+rs.getString(1));
            }
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        potongan = new javax.swing.JTextField();
        bersih = new javax.swing.JTextField();
        cetak = new javax.swing.JTextField();
        cetakk = new swing.Button();
        button2 = new swing.Button();
        simpan = new swing.Button();
        button4 = new swing.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new customtable.CustomTable();
        total_bersih = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1050, 520));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        potongan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(potongan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 160, 30));
        add(bersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 160, 30));

        cetak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cetakKeyReleased(evt);
            }
        });
        add(cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 160, 30));

        cetakk.setBackground(new java.awt.Color(255, 202, 73));
        cetakk.setForeground(new java.awt.Color(82, 82, 82));
        cetakk.setText("Cetak");
        cetakk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cetakk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakkActionPerformed(evt);
            }
        });
        add(cetakk, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 70, 30));

        button2.setBackground(new java.awt.Color(105, 152, 171));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setText("Bersih");
        button2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 70, 30));

        simpan.setBackground(new java.awt.Color(73, 255, 90));
        simpan.setForeground(new java.awt.Color(255, 255, 255));
        simpan.setText("Simpan");
        simpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 70, 30));

        button4.setBackground(new java.awt.Color(105, 152, 171));
        button4.setForeground(new java.awt.Color(255, 255, 255));
        button4.setText("Kembali");
        button4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 190, 40));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 80, 460, 190));
        add(total_bersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 324, 180, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageForm/AdminTotalBersih.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void cetakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cetakKeyReleased
        // TODO add your handling code here:
        try {
            int har = Integer.parseInt(cetak.getText());
        } catch (NumberFormatException ex) {
            cetak.setText(null);
        }
    }//GEN-LAST:event_cetakKeyReleased

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            new FormAdminReport().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FormAdminTotalBersih.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button4ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:

        try {
            String sql = "select sum(pembayaran) - '" + potongan.getText() + "' from transaksi";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                bersih.setText(rs.getString(1));
            }
        } catch (SQLException e) {
        }
 
    }//GEN-LAST:event_button2ActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "insert into income (waktu,pendapatan_bersih) values (CURRENT_TIMESTAMP()," + bersih.getText() + ")";
            conn = (Connection) koneksi.configDB();
            pst = conn.prepareStatement(sql);
            pst.execute();
            table();
            simpan sp = new simpan();
            sp.setVisible(true);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        initTotal();
    }//GEN-LAST:event_simpanActionPerformed

    private void cetakkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakkActionPerformed
        java.sql.Connection con = null;
        try {
            String jdbcDriver = "com.mysql.jdbc.Driver";
            Class.forName(jdbcDriver);

            String url = "jdbc:mysql://localhost:3306/mbaknis";
            String user = "root";
            String pass = "";

            con = DriverManager.getConnection(url, user, pass);
            Statement stm = con.createStatement();

            try {
                String report = ("D:\\Project WSIBD\\MbakNis\\src\\formAdmin\\report1.jrxml");
                HashMap hash = new HashMap();
                hash.put("kode", cetak.getText());
                JasperReport JRpt = JasperCompileManager.compileReport(report);
                JasperPrint JPrint = JasperFillManager.fillReport(JRpt, hash, con);
                JasperViewer.viewReport(JPrint, false);
            } catch (Exception e) {
                System.out.println("Gagal Untuk Di Report");
            }

        } catch (Exception e) {
        }
        potongan.setText("");
        bersih.setText("");
        cetak.setText("");
    }//GEN-LAST:event_cetakkActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int baris = table.getSelectedRow();
        if (baris != 1);
        {
            String no = table.getValueAt(baris, 0).toString();
            cetak.setText(no);
        }
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bersih;
    private swing.Button button2;
    private swing.Button button4;
    private javax.swing.JTextField cetak;
    private swing.Button cetakk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField potongan;
    private swing.Button simpan;
    private customtable.CustomTable table;
    private javax.swing.JLabel total_bersih;
    // End of variables declaration//GEN-END:variables

    public void table() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Pendapatan Bersih");
        model.addColumn("Pendapatan Bersih");
        model.addColumn("Waktu");

        try {
            String sql = "SELECT * FROM income";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/mbaknis", "root", "");
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1),
                    rs.getString(2), rs.getString(3)
                });
                table.setModel(model);
            }
        } catch (SQLException e) {
        }
    }
}
