/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formAdmin;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import pesanDialog.BerhasilHapus;
import pesanDialog.BerhasilUbah;
import pesanDialog.GagalHapus;
import pesanDialog.GagalUbah;

/**
 *
 * @author HP
 */
public class FormAdminDetailStok extends javax.swing.JPanel {

    Connection conn;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form FormAdminDetailStok
     */
    public FormAdminDetailStok() {
        initComponents();
        table.fixTable(jScrollPane1);
        DefaultTableModel mode = (DefaultTableModel) table.getModel();
        table();
        id_menu.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_simpan = new swing.Button();
        btn_refresh = new swing.Button();
        btn_ubah1 = new swing.Button();
        btn_hapus = new swing.Button();
        id_menu = new javax.swing.JTextField();
        nama_menu = new javax.swing.JTextField();
        harga_menu = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new customtable.CustomTable();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1050, 520));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_simpan.setBackground(new java.awt.Color(105, 152, 171));
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("Kembali");
        btn_simpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 420, 130, 40));

        btn_refresh.setBackground(new java.awt.Color(255, 202, 73));
        btn_refresh.setForeground(new java.awt.Color(82, 82, 82));
        btn_refresh.setText("Refresh Table");
        btn_refresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, 130, 30));

        btn_ubah1.setBackground(new java.awt.Color(73, 255, 90));
        btn_ubah1.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubah1.setText("Ubah");
        btn_ubah1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ubah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubah1ActionPerformed(evt);
            }
        });
        add(btn_ubah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 170, 40));

        btn_hapus.setBackground(new java.awt.Color(255, 61, 61));
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("Hapus");
        btn_hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 170, 40));

        id_menu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id_menu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                id_menuKeyReleased(evt);
            }
        });
        add(id_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 220, 30));
        add(nama_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 220, 30));

        harga_menu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                harga_menuKeyReleased(evt);
            }
        });
        add(harga_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 220, 30));

        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlahKeyReleased(evt);
            }
        });
        add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 220, 30));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 550, 290));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageForm/AdminDetailStok.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1050, 520));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyReleased
        // TODO add your handling code here:
        try {
            int har = Integer.parseInt(jumlah.getText());
        } catch (NumberFormatException ex) {
            jumlah.setText(null);
        }
    }//GEN-LAST:event_jumlahKeyReleased

    private void harga_menuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_harga_menuKeyReleased
        // TODO add your handling code here:
        try {
            int har = Integer.parseInt(harga_menu.getText());
        } catch (NumberFormatException ex) {
            harga_menu.setText(null);
        }
    }//GEN-LAST:event_harga_menuKeyReleased

    private void id_menuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_menuKeyReleased
        // TODO add your handling code here:
        try {
            Statement state = conn.createStatement();
            String sql = "SELECT * FROM stok_menu WHERE id_menu = '" + id_menu.getText() + "'";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/mbaknis", "root", "");
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            table();
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Menu");
            model.addColumn("Jumlah Menu");
            model.addColumn("Nama Menu");
            model.addColumn("Harga");
            rs = state.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1),
                    rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)
                });
                table.setModel(model);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_id_menuKeyReleased

    private void btn_ubah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubah1ActionPerformed
        try {
            String sql = "UPDATE stok_menu SET id_menu = '" + id_menu.getText() + "', nama_menu = '" + nama_menu.getText() + "',harga_menu = '" + harga_menu.getText() + "',jumlah_menu = '" + jumlah.getText() + "' WHERE id_menu = " + id_menu.getText() + "";
            conn = (Connection) koneksi.configDB();
            pst = conn.prepareStatement(sql);
            pst.execute();
            BerhasilUbah ub = new BerhasilUbah();
            ub.setVisible(true);
            table();
        } catch (Exception e) {
            GagalUbah gu = new GagalUbah();
            gu.setVisible(true);
        }
        id_menu.setText("");
        nama_menu.setText("");
        harga_menu.setText("");
        jumlah.setText("");
    }//GEN-LAST:event_btn_ubah1ActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        try {
            String sql = "DELETE from stok_menu where id_menu = " + id_menu.getText();
            conn = (Connection) koneksi.configDB();
            pst = conn.prepareStatement(sql);
            pst.execute();
            BerhasilHapus bh = new BerhasilHapus();
            bh.setVisible(true);
        } catch (Exception e) {
            GagalHapus gh = new GagalHapus();
            gh.setVisible(true);
        }
        table();
        id_menu.setText("");
        nama_menu.setText("");
        harga_menu.setText("");
        jumlah.setText("");
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        table();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        this.setVisible(false);
        new FormAdminStockAvailable().setVisible(true);
        id_menu.setText("");
        nama_menu.setText("");
        harga_menu.setText("");
        jumlah.setText("");
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int baris = table.getSelectedRow();
        if (baris != 1);
        {
            String no = table.getValueAt(baris, 0).toString();
            id_menu.setText(no);
            String nama = table.getValueAt(baris, 1).toString();
            nama_menu.setText(nama);
            String har = table.getValueAt(baris, 2).toString();
            harga_menu.setText(har);
            String jum = table.getValueAt(baris, 3).toString();
            jumlah.setText(jum);
        }
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btn_hapus;
    private swing.Button btn_refresh;
    private swing.Button btn_simpan;
    private swing.Button btn_ubah1;
    private javax.swing.JTextField harga_menu;
    private javax.swing.JTextField id_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField nama_menu;
    private customtable.CustomTable table;
    // End of variables declaration//GEN-END:variables

    public void table() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Menu");
        model.addColumn("Nama Menu");
        model.addColumn("Harga Menu");
        model.addColumn("Jumlah Menu");
        model.addColumn("Tanggal Penambahan Stok");

        try {
            String sql = "SELECT id_menu,nama_menu,harga_menu,jumlah_menu,waktu FROM stok_menu";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/mbaknis", "root", "");
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1),
                    rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)
                });
                table.setModel(model);
            }
        } catch (SQLException e) {
        }
    }
}
