/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formAdmin;

import koneksi.koneksi;
import com.barcodelib.barcode.Linear;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import pesanDialog.GagalSimpan;
import pesanDialog.simpan;
import transisi.TransisiForm;

/**
 *
 * @author KRISNA
 */
public class FormAdminStockAvailable extends TransisiForm {

    FormAdminDetailStok ds;
    Connection conn;
    ResultSet rs = null;
    PreparedStatement pst = null;
    JasperReport jasper;
    JasperPrint jaspri;
    Map param = new HashMap();
    JasperDesign jasdes;

    /**
     * Creates new form Form
     */
    public FormAdminStockAvailable() {
        initComponents();
        showPieChart();
        ds = new FormAdminDetailStok();
        panelDetailStok.add(ds);
        ds.setVisible(false);
    }

    public void showPieChart() {

        //create dataset
        try {
            String sql = "select * from stok_menu";
            java.sql.Connection konek = (Connection) koneksi.configDB();
            java.sql.PreparedStatement pst = konek.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            DefaultPieDataset dataset = new DefaultPieDataset();
            JFreeChart chart = ChartFactory.createPieChart("Pie Chart", dataset);
            ChartFrame frame = new ChartFrame("Coba Pie Chart", chart);
            frame.setSize(20, 20);
            ChartPanel barChartPanel = new ChartPanel(chart);
            barChartPanel.setMaximumDrawWidth(400);
            barChartPanel.setPreferredSize(new Dimension(400, 333));
            panelchart.removeAll();
            panelchart.add(barChartPanel, BorderLayout.CENTER);
            panelchart.validate();
            while (rs.next()) {
                String nama_makanan = rs.getString(3);
                int stok = Integer.parseInt(rs.getString(2));
                dataset.setValue(nama_makanan, stok);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDetailStok = new javax.swing.JPanel();
        btn_detail = new swing.Button();
        btn_simpan = new swing.Button();
        jumlah = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        nama_menu = new javax.swing.JTextField();
        txtInvoice = new javax.swing.JTextField();
        panelchart = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDetailStok.setOpaque(false);
        add(panelDetailStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1050, 530));

        btn_detail.setBackground(new java.awt.Color(105, 152, 171));
        btn_detail.setForeground(new java.awt.Color(255, 255, 255));
        btn_detail.setText("Detail");
        btn_detail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detailActionPerformed(evt);
            }
        });
        add(btn_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 160, 40));

        btn_simpan.setBackground(new java.awt.Color(73, 255, 90));
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("Simpan");
        btn_simpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 360, 40));

        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlahKeyReleased(evt);
            }
        });
        add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 200, 30));

        harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hargaKeyReleased(evt);
            }
        });
        add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 200, 30));
        add(nama_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 200, 30));
        add(txtInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 200, 30));

        panelchart.setPreferredSize(new java.awt.Dimension(300, 300));
        add(panelchart, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 400, 340));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageForm/AdminStokMenu.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void hargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaKeyReleased
        // TODO add your handling code here:
        try {
            int har = Integer.parseInt(harga.getText());
        } catch (NumberFormatException ex) {
            harga.setText(null);
        }
    }//GEN-LAST:event_hargaKeyReleased

    private void jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyReleased
        // TODO add your handling code here:
        try {
            int har = Integer.parseInt(jumlah.getText());
        } catch (NumberFormatException ex) {
            jumlah.setText(null);
        }
    }//GEN-LAST:event_jumlahKeyReleased

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        try {
            String sql = "insert into stok_menu (waktu,id_menu,nama_menu,harga_menu,jumlah_menu) values (CURRENT_TIMESTAMP(),?,?,?,?)";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/mbaknis", "root", "");
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtInvoice.getText());
            stat.setString(2, nama_menu.getText());
            stat.setString(3, harga.getText());
            stat.setString(4, jumlah.getText());
            stat.executeUpdate();
            //            FormAdminDetailStok ds = new FormAdminDetailStok();
            //            ds.table();
            simpan sp = new simpan();
            sp.setVisible(true);
            Linear barcode = new Linear();
            barcode.setType(Linear.CODE128);
            barcode.setData(txtInvoice.getText());
            barcode.setI(11.0f);
            String fname = txtInvoice.getText();
            barcode.renderBarcode("src/ImageBarcode/" + fname + ".png");

            File file = new File("src/report/cetakBarcode.jrxml");
            jasdes = JRXmlLoader.load(file);
            param.put("no_invoice", txtInvoice.getText());
            param.put("realPath", "src/ImageBarcode/" + txtInvoice.getText() + ".png");
            jasper = JasperCompileManager.compileReport(jasdes);
            jaspri = JasperFillManager.fillReport(jasper, param, conn);
            JasperViewer jasperviewer = new JasperViewer(jaspri, false);
            jasperviewer.setExtendedState(jasperviewer.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
            jasperviewer.setVisible(true);
        } catch (Exception e) {
            GagalSimpan gs = new GagalSimpan();
            gs.setVisible(true);
        }
        showPieChart();
        txtInvoice.setText("");
        nama_menu.setText("");
        harga.setText("");
        jumlah.setText("");
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detailActionPerformed
        ds.setVisible(true);
    }//GEN-LAST:event_btn_detailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btn_detail;
    private swing.Button btn_simpan;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField nama_menu;
    private javax.swing.JPanel panelDetailStok;
    private javax.swing.JPanel panelchart;
    private javax.swing.JTextField txtInvoice;
    // End of variables declaration//GEN-END:variables

}
