/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formStaff;

import koneksi.koneksi;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import pesanDialog.GagalDitemukan;
import pesanDialog.simpan;
import transisi.TransisiForm;

/**
 *
 * @author KRISNA
 */
public class FormStaffAttendance extends TransisiForm {

    Timer updateTimer;
    int DELAY = 100;

    /**
     * Creates new form formStaffDashboard
     */
    public FormStaffAttendance() {
        initComponents();
        absen.requestFocus();
        updateTimer = new Timer(DELAY, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date currentTime = new Date();
                String formatTimerStr = "HH:mm:ss";
                DateFormat formatTime = new SimpleDateFormat(formatTimerStr);
                String formattedTimeStr = formatTime.format(currentTime);
                jLabel3.setText(formattedTimeStr);
            }
        });
        updateTimer.start();
    }

    public void absendek() {
        try {
            String sql = "insert into absen(waktu_absen,kode_staff) VALUES(CURRENT_TIMESTAMP()," + absen.getText() + ")";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            simpan sp = new simpan();
            sp.setVisible(true);
        } catch (HeadlessException | SQLException e) {
            GagalDitemukan gd = new GagalDitemukan();
            gd.setVisible(true);
        }
        absen.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        absen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        absen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                absenKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                absenKeyReleased(evt);
            }
        });
        add(absen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 160, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(82, 82, 82));
        jLabel3.setText("00:00:00");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 220, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageForm/StaffAbsen.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void absenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_absenKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            absendek();
        }
        try {
            int id = Integer.parseInt(absen.getText());
        } catch (NumberFormatException ex) {
            absen.setText(null);
        }
    }//GEN-LAST:event_absenKeyReleased

    private void absenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_absenKeyPressed
        // TODO add your handling code here:
//        try {
//            String sql = "insert into absen(waktu_absen,kode_staff) VALUES(CURRENT_TIMESTAMP()," + absen.getText() + ")";
//            java.sql.Connection conn = (Connection) koneksi.configDB();
//            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
//            pst.execute();
//            simpan sp = new simpan();
//            sp.setVisible(true);
//        } catch (HeadlessException | SQLException e) {
//            GagalDitemukan gd = new GagalDitemukan();
//            gd.setVisible(true);
//        }
//        absen.setText("");
    }//GEN-LAST:event_absenKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField absen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
