/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formStaff;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author HP
 */
public class FormStaffCetakStruk extends javax.swing.JPanel {

    Connection conn;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form FormAdminDetailStok
     */
    public FormStaffCetakStruk() {
        initComponents();
        table.fixTable(jScrollPane1);
        DefaultTableModel mode = (DefaultTableModel) table.getModel();
        table();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_detail1 = new swing.Button();
        btn_detail = new swing.Button();
        txt_cetak = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new customtable.CustomTable();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1050, 520));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_detail1.setBackground(new java.awt.Color(73, 255, 90));
        btn_detail1.setForeground(new java.awt.Color(255, 255, 255));
        btn_detail1.setText("Cetak");
        btn_detail1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_detail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detail1ActionPerformed(evt);
            }
        });
        add(btn_detail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 360, 40));

        btn_detail.setBackground(new java.awt.Color(102, 102, 255));
        btn_detail.setForeground(new java.awt.Color(255, 255, 255));
        btn_detail.setText("Kembali");
        btn_detail.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detailActionPerformed(evt);
            }
        });
        add(btn_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 410, 160, 30));
        add(txt_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 250, 30));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 540, 290));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageForm/StaffCetakStruk.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1050, 520));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detailActionPerformed
        this.setVisible(false);
        txt_cetak.setText("");

    }//GEN-LAST:event_btn_detailActionPerformed

    private void btn_detail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detail1ActionPerformed
        // TODO add your handling code here:
        java.sql.Connection con = null;
        try {
            String jdbcDriver = "com.mysql.jdbc.Driver";
            Class.forName(jdbcDriver);

            String url = "jdbc:mysql://localhost:3306/mbaknis";
            String user = "root";
            String pass = "";

            con = DriverManager.getConnection(url, user, pass);
            Statement stm = con.createStatement();

            try {
                String report = ("C:\\Users\\HP\\Documents\\NetBeansProjects\\MbakNis\\src\\formStaff\\newReport.jrxml");
                HashMap hash = new HashMap();
                hash.put("kode", txt_cetak.getText());
                JasperReport JRpt = JasperCompileManager.compileReport(report);
                JasperPrint JPrint = JasperFillManager.fillReport(JRpt, hash, con);
                JasperViewer.viewReport(JPrint, false);
            } catch (Exception e) {
                System.out.println("Gagal Untuk Di Report");
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_detail1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btn_detail;
    private swing.Button btn_detail1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private customtable.CustomTable table;
    private javax.swing.JTextField txt_cetak;
    // End of variables declaration//GEN-END:variables

    public void table() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID transaksi");
        model.addColumn("Nama Pelanggan");
        model.addColumn("Tanggal Keluar");
        model.addColumn("Pembayaran");
        model.addColumn("Jumlah Beli");
        model.addColumn("Nama Produk");

        try {
            String sql = "SELECT transaksi.`id_kr`,transaksi.`nama_pelanggan`,transaksi.`tanggal_keluar`,transaksi.`pembayaran`,detail_transaksi.`jumlah_beli`,detail_transaksi.`nama_produk`\n"
                    + "FROM transaksi\n"
                    + "JOIN detail_transaksi\n"
                    + "ON transaksi.`id_kr` = detail_transaksi.`id_kr`";
            java.sql.Connection konek = (Connection) koneksi.configDB();
            pst = konek.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1),
                    rs.getString(2), rs.getString(3)
                });
                table.setModel(model);
            }
        } catch (SQLException e) {
        }
    }
}
