package FormLoginRegister;

import PesanDialog.BerhasilLoginAdmin;
import PesanDialog.BerhasilLoginStaff;
import PesanDialog.BerhasilRegister;
import PesanDialog.GagalLogin;
import PesanDialog.GagalRegister;
import formAdmin.FormAdminDashboard;
import formStaff.FormStaffDashboard;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import main.MainAdmin;
import main.MainStaff;
import org.jdesktop.animation.timing.Animator;
import org.jdesktop.animation.timing.TimingTarget;
import org.jdesktop.animation.timing.TimingTargetAdapter;

/**
 *
 * @author KRISNA
 */
public class LoginMain extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st = null;

    private Animator animatorLogin;
    private Animator animatorBody;
    private boolean signIn;

    public LoginMain() {
        initComponents();
        this.showPassword.setVisible(false);
        this.showPassword1.setVisible(false);

        getContentPane().setBackground(new Color(245, 245, 245));
        TimingTarget targetLogin = new TimingTargetAdapter() {
            @Override
            public void timingEvent(float fraction) {
                if (signIn) {
                    background1.setAnimate(fraction);
                } else {
                    background1.setAnimate(1f - fraction);
                }
            }

            @Override
            public void end() {
                if (signIn) {
                    panelLogin.setVisible(false);
                    background1.setShowPaint(true);
                    panelBody.setAlpha(0);
                    panelBody.setVisible(true);
                    animatorBody.start();
                } else {
                    enableLogin(true);
                    txt_username.grabFocus();
                }
//                
            }

        };
        TimingTarget targetBody = new TimingTargetAdapter() {
            @Override
            public void timingEvent(float fraction) {
                if (signIn) {
                    panelBody.setAlpha(fraction);
                } else {
                    panelBody.setAlpha(1f - fraction);
                }
            }

            @Override
            public void end() {
                if (signIn == false) {
                    panelBody.setVisible(false);
                    background1.setShowPaint(false);
                    background1.setAnimate(1);
                    panelLogin.setVisible(true);
                    animatorLogin.start();
                }
            }

        };
        animatorLogin = new Animator(1500, targetLogin);
        animatorBody = new Animator(1500, targetBody);
        animatorLogin.setResolution(0);
        animatorBody.setResolution(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new swing.Background();
        panelLogin = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        iconMartabak = new javax.swing.JLabel();
        txt_password = new swing.PasswordField();
        txt_username = new swing.TextField();
        btn_register = new swing.Button();
        btn_login = new swing.Button();
        Label_TidakPunyaAkun = new javax.swing.JLabel();
        Label_SelamatDatang = new javax.swing.JLabel();
        showPassword = new javax.swing.JLabel();
        hidePassword = new javax.swing.JLabel();
        iconLogin1 = new javax.swing.JLabel();
        panelBody = new swing.PanelTransparent();
        jPanel2 = new javax.swing.JPanel();
        roleComboBox1 = new combobox.ComboBox();
        jLabel4 = new javax.swing.JLabel();
        txt_password1 = new swing.PasswordField();
        btn_masuk = new swing.Button();
        button2 = new swing.Button();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        showPassword1 = new javax.swing.JLabel();
        hidePassword1 = new javax.swing.JLabel();
        iconLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background1.setLayout(new java.awt.CardLayout());

        panelLogin.setOpaque(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconMartabak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo martabak.png"))); // NOI18N
        jPanel1.add(iconMartabak, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 120, 560, 290));

        txt_password.setBackground(new java.awt.Color(245, 245, 245));
        txt_password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_password.setLabelText("Password");
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 310, 60));

        txt_username.setBackground(new java.awt.Color(245, 245, 245));
        txt_username.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_username.setLabelText("Username");
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 310, 60));

        btn_register.setBackground(new java.awt.Color(82, 82, 82));
        btn_register.setForeground(new java.awt.Color(255, 255, 255));
        btn_register.setText("Register");
        btn_register.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        jPanel1.add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 310, 40));

        btn_login.setBackground(new java.awt.Color(82, 82, 82));
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Login");
        btn_login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 310, 40));

        Label_TidakPunyaAkun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pertanyaan1.png"))); // NOI18N
        jPanel1.add(Label_TidakPunyaAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 310, 20));

        Label_SelamatDatang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/SelamatDatang.png"))); // NOI18N
        jPanel1.add(Label_SelamatDatang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 600, 60));

        showPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/showpassword.png"))); // NOI18N
        showPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showPasswordMousePressed(evt);
            }
        });
        jPanel1.add(showPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 40, 40));

        hidePassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hidePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hidepassword.png"))); // NOI18N
        hidePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hidePasswordMousePressed(evt);
            }
        });
        jPanel1.add(hidePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 40, 40));

        iconLogin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconLogin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/usernamelogin.png"))); // NOI18N
        iconLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconLogin1MousePressed(evt);
            }
        });
        jPanel1.add(iconLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 40, 40));

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        background1.add(panelLogin, "card2");

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roleComboBox1.setBackground(new java.awt.Color(245, 245, 245));
        roleComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Staff" }));
        roleComboBox1.setSelectedIndex(-1);
        roleComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        roleComboBox1.setLabeText("Role");
        jPanel2.add(roleComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 310, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo martabak.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 130, 560, 290));

        txt_password1.setBackground(new java.awt.Color(245, 245, 245));
        txt_password1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_password1.setLabelText("Password");
        jPanel2.add(txt_password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 310, 60));

        btn_masuk.setBackground(new java.awt.Color(82, 82, 82));
        btn_masuk.setForeground(new java.awt.Color(255, 255, 255));
        btn_masuk.setText("Masuk");
        btn_masuk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masukActionPerformed(evt);
            }
        });
        jPanel2.add(btn_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 310, 40));

        button2.setBackground(new java.awt.Color(82, 82, 82));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setText("Daftar");
        button2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel2.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 310, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pertanyaan2.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 310, 20));

        txt_username1.setBackground(new java.awt.Color(245, 245, 245));
        txt_username1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_username1.setLabelText("Username");
        jPanel2.add(txt_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 310, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/DaftarAkun.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 600, 60));

        showPassword1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showPassword1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/showpassword.png"))); // NOI18N
        showPassword1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showPassword1MousePressed(evt);
            }
        });
        jPanel2.add(showPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 40, 40));

        hidePassword1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hidePassword1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hidepassword.png"))); // NOI18N
        hidePassword1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hidePassword1MousePressed(evt);
            }
        });
        jPanel2.add(hidePassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 40, 40));

        iconLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/usernamelogin.png"))); // NOI18N
        iconLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconLoginMousePressed(evt);
            }
        });
        jPanel2.add(iconLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 40, 40));

        javax.swing.GroupLayout panelBodyLayout = new javax.swing.GroupLayout(panelBody);
        panelBody.setLayout(panelBodyLayout);
        panelBodyLayout.setHorizontalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBodyLayout.setVerticalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBodyLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        background1.add(panelBody, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        if (!animatorLogin.isRunning()) {
            signIn = true;

            boolean action = true;

            if (action) {
                animatorLogin.start();

            }
        }

    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        try {
            String sql = "SELECT * FROM login WHERE username='" + txt_username.getText() + "' && password ='"
                    + txt_password.getText() + "';";
            con = DriverManager.getConnection("jdbc:mysql://localhost/mbaknis", "root", "");
            pst = con.prepareStatement(sql);
            st = con.createStatement();
            rs = pst.executeQuery();
            if (rs.next()) {
                if (rs.getString("role").equals("Admin")) {
                    BerhasilLoginAdmin admin = new BerhasilLoginAdmin();
                    admin.setVisible(true);
                    this.setVisible(false);

                } else {
                    BerhasilLoginStaff staff = new BerhasilLoginStaff();
                    staff.setVisible(true);
                    this.setVisible(false);

                }

            } else {

                if (!animatorLogin.isRunning()) {
                    signIn = true;
                    String user = txt_username.getText().trim();
                    String pass = String.valueOf(txt_password.getPassword());
                    boolean action = true;
                    if (user.equals("")) {
                        txt_username.setHelperText("Harap masukkan username anda");
                        txt_username.grabFocus();
                        action = false;
                    }
                    if (pass.equals("")) {
                        txt_password.setHelperText("Harap masukkan password anda");
                        if (action) {
                            txt_password.grabFocus();
                        }
                        action = false;
                    }
                    if (action) {
                        GagalLogin login = new GagalLogin();
                        login.setVisible(true);
                        enableLogin(true);
                        txt_username.setText("");
                        txt_password.setText("");
                    }

                }
            }

            sql = "SELECT * FROM login where username = '" + txt_username.getText() + "' "
                    + "and password ='" + txt_password.getText() + "'";
            try {
                st = con.createStatement();
                rs = pst.executeQuery(sql);
                if (rs.next()) {
                    FormAdminDashboard.nameShow.setText(rs.getString(2));
                    FormAdminDashboard.roleShow.setText(rs.getString(4));
                    FormStaffDashboard.nameShow.setText(rs.getString(2));
                    FormStaffDashboard.roleShow.setText(rs.getString(4));

                } else {
                    System.out.println("Error");
                }
            } catch (Exception e) {
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
//            GagalRegister gr = new GagalRegister();
//            gr.setVisible(true);
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        try {
            String sql = "INSERT INTO login(username, password, role) VALUES (?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost/mbaknis", "root", "");
            pst = con.prepareStatement(sql);
            pst.setString(1, txt_username1.getText());
            pst.setString(2, txt_password1.getText());
            pst.setString(3, String.valueOf(roleComboBox1.getSelectedItem()));
            pst.execute();

            if (!animatorLogin.isRunning()) {
                signIn = true;
                String user = txt_username1.getText().trim();
                String pass = String.valueOf(txt_password1.getPassword());
                boolean action = true;
                if (user.equals("")) {
                    txt_username1.setHelperText("Harap masukkan username anda");
                    txt_username1.grabFocus();
                    action = false;
                }
                if (pass.equals("")) {
                    txt_password1.setHelperText("Harap masukkan password anda");
                    if (action) {
                        txt_password1.grabFocus();
                    }
                    action = false;
                }
                if (action) {
                    BerhasilRegister br = new BerhasilRegister();
                    br.setVisible(true);
                    signIn = false;
                    clearLogin();
                    animatorBody.start();
                }

            }
            txt_username1.setText("");
            txt_password1.setText("");

        } catch (Exception ex) {
            GagalRegister gr = new GagalRegister();
            gr.setVisible(true);
//            JOptionPane.showMessageDialog(this, ex);
        }

    }//GEN-LAST:event_button2ActionPerformed

    private void btn_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masukActionPerformed
        signIn = false;
        clearLogin();
        animatorBody.start();
        txt_username1.setText("");
        txt_password1.setText("");
    }//GEN-LAST:event_btn_masukActionPerformed

    private void hidePasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePasswordMousePressed
        showPassword.setVisible(true);
        hidePassword.setVisible(false);
        txt_password.setEchoChar((char) 0);
    }//GEN-LAST:event_hidePasswordMousePressed

    private void showPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPasswordMousePressed
        hidePassword.setVisible(true);
        showPassword.setVisible(false);
        txt_password.setEchoChar('*');
    }//GEN-LAST:event_showPasswordMousePressed

    private void showPassword1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPassword1MousePressed
        hidePassword1.setVisible(true);
        showPassword1.setVisible(false);
        txt_password1.setEchoChar('*');
    }//GEN-LAST:event_showPassword1MousePressed

    private void hidePassword1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePassword1MousePressed
        showPassword1.setVisible(true);
        hidePassword1.setVisible(false);
        txt_password1.setEchoChar((char) 0);
    }//GEN-LAST:event_hidePassword1MousePressed

    private void iconLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconLoginMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_iconLoginMousePressed

    private void iconLogin1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconLogin1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_iconLogin1MousePressed

    private void enableLogin(boolean action) {
        txt_username.setEditable(action);
        txt_password.setEditable(action);
        btn_login.setEnabled(action);
    }

    public void clearLogin() {
        txt_username.setText("");
        txt_password.setText("");
        txt_username.setHelperText("");
        txt_password.setHelperText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_SelamatDatang;
    private javax.swing.JLabel Label_TidakPunyaAkun;
    private swing.Background background1;
    private swing.Button btn_login;
    private swing.Button btn_masuk;
    private swing.Button btn_register;
    private swing.Button button2;
    private javax.swing.JLabel hidePassword;
    private javax.swing.JLabel hidePassword1;
    private javax.swing.JLabel iconLogin;
    private javax.swing.JLabel iconLogin1;
    private javax.swing.JLabel iconMartabak;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private swing.PanelTransparent panelBody;
    private javax.swing.JPanel panelLogin;
    private combobox.ComboBox roleComboBox1;
    private javax.swing.JLabel showPassword;
    private javax.swing.JLabel showPassword1;
    private swing.PasswordField txt_password;
    private swing.PasswordField txt_password1;
    private swing.TextField txt_username;
    public static final swing.TextField txt_username1 = new swing.TextField();
    // End of variables declaration//GEN-END:variables
}
